movie_library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('movies.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.MovieView.as_view()),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor_detail'),
]

movies/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Категории фильмов"""
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug': self.name})

    class Meta:
        verbose_name = 'Актеры и режиссеры'
        verbose_name_plural = 'Актеры и режиссеры'


class Genre(models.Model):
    """Жанры"""
    name = models.CharField('Название', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Movie(models.Model):
    """Фильмы"""
    title = models.CharField('Название', max_length=100)
    tagline = models.CharField('Слоган', max_length=100, default='')
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Дата выхода', default=2019)
    country = models.CharField('Страна', max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name='режиссер', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='актеры', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='жанры')
    world_premier = models.DateField('Премьера в мире', default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default=0, help_text='уазывать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='уазывать сумму в долларах')
    fees_in_world = models.PositiveIntegerField('Сборы в мире', default=0, help_text='уазывать сумму в долларах')
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField('Заголовок', max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, verbose_name='фильм', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Кадр из фильма'
        verbose_name_plural = 'Кадры из фильма'


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField('Значение', default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField('IP-адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='фильм')

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='фильм')

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

movies/forms.py
from django import forms

from .models import Reviews


class ReviewForm(forms.ModelForm):
	"""Форма отзывов"""
	class Meta:
		model = Reviews
		fields = ('email', 'name', 'text')

movies/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import Movie, Actor
from .forms import ReviewForm


class MovieView(ListView):
    """Список фильмов"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)


class MovieDetailView(DetailView):
    """Полное описание фильма"""
    model = Movie
    slug_field = 'url'


class AddReview(View):
    """Отзывы"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(pk=pk)
        if form.is_valid():
            review = form.save(commit=False)
            if request.POST.get('parent', None):
                review.parent_id = int(request.POST.get('parent'))
            review.movie = movie
            review.save()
        return redirect(movie.get_absolute_url())


class ActorView(DetailView):
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = 'name'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>{% block title %} {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <!-- //font-awesome-icons -->
  <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">
    <!-- //Fonts -->
</head>

<body>
    <div id="page" class="page">
        {% include 'include/header.html' %}

        {% block content %}
        
        {% endblock %}

        {% include 'include/footer.html' %}
    </div>
    
</body>
</html>

templates/include/footer.html
<footer class="editContent">
    <div class="container">
        <div class="row footer-top">
            <div class="col-lg-4 footer-grid_section_w3layouts">
                <h2 class="logo-2 mb-lg-4 mb-3">
                    <a href="index.html" class="editContent">
                        <span class="fa" aria-hidden="true" >
                            Django School
                        </span>
                    </a>
                </h2>
                <p class="editContent" >
                    Канал для программистов и людей, которые хотят развиваться в сфере IT.
                    Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                    и многое другое.
                </p>
                <h4 class="sub-con-fo ad-info my-4 editContent" >Catch on Social</h4>
                <ul class="w3layouts_social_list media-soc list-unstyled">
                    <li>
                        <a href="#" class="w3pvt_facebook editContent" >
                            <span class="fa fa-facebook-f" ></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_twitter editContent" >
                            <span class="fa fa-twitter" ></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_dribble editContent" >
                            <span class="fa fa-dribbble" ></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_google editContent" >
                            <span class="fa fa-google-plus" ></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8 footer-right">
                <div class="w3layouts-news-letter">
                    <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Newsletter</h3>

                    <p class="editContent" >By subscribing to our mailing list you will always get latest news and updates from us.</p>
                    <form action="#" method="post" class="w3layouts-newsletter">
                        <input type="email" name="Email" class="editContent" placeholder="Enter your email..." required="" >
                        <button class="btn1 btn" ><span class="fa fa-paper-plane-o" aria-hidden="true" ></span></button>
                    </form>
                </div>
                <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Разделы</h3>
                        <ul class="list-unstyled w3layouts-icons">
                            <li>
                                <a href="index.html" class="editContent" >Главная</a>
                            </li>
                            <li>
                                <a href="about.html" class="editContent" >Категории</a>
                            </li>
                            <li>
                                <a href="contact.html" class="editContent" >Контакты</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <!-- social icons -->
                        <div class="agileinfo_social_icons">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Pages</h3>
                            <ul class="list-unstyled w3layouts-icons">

                                <li>
                                    <a href="#" class="editContent" >About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent" >About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent" >About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent" >About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent" >About Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- social icons -->
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                        <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent" >Contact Info</h3>
                        <div class="contact-info">
                            <div class="footer-address-inf my-4">
                                <h4 class="ad-info mb-2 editContent" >Email </h4>
                                <p class="editContent" ><a href="mailto:info@example.com">info@example.com</a></p>
                            </div>
                            <div class="footer-address-inf">
                                <h4 class="ad-info mb-2 editContent" >Location</h4>
                                <p class="editContent" >New York City</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- //footer -->
<div class="cpy-right py-3">
    <div class="container">
        <div class="row">
            <p class="col-md-10 text-left">© 2019 DjangoMovie. All rights reserved | Design by
                <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
            </p>
            <!-- move top icon -->
            <a href="#home" class="move-top text-right col-md-2"><span class="fa fa-long-arrow-up" aria-hidden="true" ></span></a>
            <!-- //move top icon -->
        </div>
    </div>
</div>

templates/include/header.html
{% load movie_tag %}

<div class="main-banner bg bg1" id="home">
    <!-- header -->
    <header class="header">
        <div class="container-fluid px-lg-5">
            <!-- nav -->
            <nav class="py-4">
                <div id="logo">
                    <h1> <a href="index.html" class="editContent" style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">DjangoMovie</a></h1>
                </div>

                <label for="drop" class="toggle">Menu</label>
                <input type="checkbox" id="drop">
                <ul class="menu mt-2">
                    <li class="active"><a href="/">Главная</a></li>
                    <li>
                        <!-- First Tier Drop Down -->
                        <label for="drop-2" class="toggle">Категории <span class="fa fa-angle-down" aria-hidden="true" ></span> </label>
                        <a href="#">Категории <span class="fa fa-angle-down" aria-hidden="true"></span></a>
                        <input type="checkbox" id="drop-2">
                        <ul>
                            {% get_categories as categories %}
                            {% for category in categories %}
                                <li><a href="/">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="contact.html" style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a></li>
                </ul>
            </nav>
            <!-- //nav -->
        </div>
    </header>
    <!-- //header -->
    <!--/banner-->
    <div class="banner-info">
        <p class="editContent" >лучший сайт на django 3</p>
        <h3 class="mb-4 editContent">Все о кино</h3>
        <div class="ban-buttons">
        </div>
    </div>
    <!--// banner-inner -->
</div>

<ol class="breadcrumb editContent">
    <li class="breadcrumb-item">
        <a href="index.html" class="editContent">Home</a>
    </li>
    <li class="breadcrumb-item active editContent">Single Page</li>
</ol>

templates/include/sidebar.html
{% load movie_tag %}

<div class="search-bar w3layouts-newsletter">
    <h3 class="sear-head editContent" >Поиск фильма</h3>
    <form action="#" method="post" class="d-flex editContent" >
        <input type="search" placeholder="Введите название..." name="search" class="form-control" required="">
        <button class="btn1 btn" ><span class="fa fa-search" aria-hidden="true" ></span></button>
    </form>
</div>
<!--preference -->
<div class="left-side my-4">
    <h3 class="sear-head editContent" >Жанры</h3>
    <ul class="w3layouts-box-list">
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >Аниме</span>
        </li>
            <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >Боевики</span>
        </li>
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >Комедии</span>
        </li>
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >Ужасы</span>
        </li>
    </ul>
</div>
<!-- // preference -->
<!-- discounts -->
<div class="left-side">
    <h3 class="sear-head editContent" >Год</h3>
    <ul class="w3layouts-box-list">
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >2020</span>
        </li>
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >2019</span>
        </li>
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >2018</span>
        </li>
        <li>
            <input type="checkbox" class="checked">
            <span class="span editContent" >2017</span>
        </li>
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >2016</span>
        </li>
        <li class="editContent" >
            <input type="checkbox" class="checked">
            <span class="span editContent" >2015</span>
        </li>
    </ul>
</div>
<!-- //discounts -->
<!-- reviews -->
<div class="customer-rev left-side my-4">
    <h3 class="sear-head editContent" >Рейтинг</h3>
    <ul class="w3layouts-box-list">
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="editContent" >5.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="editContent" >4.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star-half-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="editContent" >3.5</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="editContent" >3.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star-half-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="editContent" >2.5</span>
            </a>
        </li>
    </ul>
</div>
{% get_recent_movies count=3 %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static %}

{% block title %} {{movie.title}} {% endblock %}

{% block container %}
    <div class="container py-md-3">
{% endblock %}
    </div>

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock %}
    </div>

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none"><span><b>Год:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none"><span><b>Страна:</b> {{ movie.country }}</span></li>
                    <li style="list-style: none"><span><b>Слоган:</b> {{ movie.tagline }}</span></li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b>
                            {% for director in movie.directors.all %}
                                <a href="{{ director.get_absolute_url }}">{{ director.name }}</a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Актеры:</b>
                            {% for actor in movie.actors.all %}
                                <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Жанр:</b>
                            {% for genre in movie.genres.all %}
                                {{ genre.name }}
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premier }}</span></li>
                    <li style="list-style: none"><span><b>Бюджет:</b> {{ movie.budget }}</span></li>
                    <li style="list-style: none"><span><b>Сборы в США:</b> {{ movie.fees_in_usa }}</span></li>
                    <li style="list-style: none"><span><b>Сборы в мире:</b> {{ movie.fees_in_world }}</span></li>
                    <li style="list-style: none">
                        <a href="#"><b>Рейтинг:</b>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="editContent"
                                  style="outline: none; cursor: inherit;">5.0</span>
                        </a>
                    </li>
                </ul>
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-facebook-f"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-twitter"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-dribbble"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О фильме {{ movie.title }}</h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img class="img-movie-shots" src="{{ image.image.url }}" alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">{{ movie.description|safe }}</p>
<!--            <p class="mt-3 italic-blue editContent"-->
<!--               style="outline: none; cursor: inherit;">-->
<!--                <iframe width="560" height="315"-->
<!--                        src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"-->
<!--                        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"-->
<!--                        allowfullscreen>-->
<!--                </iframe>-->
<!--            </p>-->
<!--            <p class="mt-3 editContent" style="outline: none; cursor: inherit;">-->
<!--                Человечество дорого заплатило за технический прогресс, поставив под-->
<!--                угрозу свое выживание.-->
<!--                Пришло время покончить с войной между машинами и людьми.-->
<!--                Научно-фантастический боевик,-->
<!--                заключительная часть трилогии, перезапускающей франшизу «Терминатора»-->
<!--                Джеймса Кэмерона.-->
<!--            </p>-->
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent"><span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>
                        Оставить отзыв
                    </h3>
                    <form action="{% url 'add_review' movie.pk %}" method="POST" class="mt-4" id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">Ваш комментарий *</label>
                            <textarea class="form-control border" rows="5" name="text" id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">Имя *</label>
                                <input type="text" class="form-control border" name="name" id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">Email *</label>
                                <input type="email" class="form-control border" name="email" id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit" class="mt-3 btn btn-success btn-block py-3">Отправить</button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
            {% for review in movie.get_review %}
                <div class="media py-5">
                    <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                    <div class="media-body mt-4">
                        <h5 class="mt-0 editContent">{{ review.name }}</h5>
                        <p class="mt-2 editContent">{{ review.text }}</p>
                        <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}');">Ответить</a>
                        {% for rew in review.reviews_set.all %}
                            <div class="media mt-5 editContent">
                                <a class="pr-3" href="#">
                                    <img src="{% static 'images/te1.jpg' %}" class="img-fluid" alt="image">
                                </a>
                                <div class="media-body">
                                    <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                    <p class="mt-2 editContent">{{ rew.text }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script type="text/javascript">
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `;            
        }
    </script>
{% endblock %}